list: $/marketplace/tokens/models/token/columns.yaml
modelClass: Marketplace\Tokens\Models\Token
title: Token
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'marketplace/tokens/token/update/:id'
filter: $/marketplace/tokens/models/token/scopes.yaml
